import io
import os
import re
import sys
import json
import tempfile
from textwrap import dedent
from tkinter import Tk, simpledialog, messagebox
from string import Template

# pip installs needed for this builder (not for the Space runtime)
#   pip install huggingface_hub==0.24.6  (or newer)
from huggingface_hub import HfApi, create_repo, upload_file

# ----------------------------
# Minimal helpers
# ----------------------------
def slugify(name: str) -> str:
    s = name.strip().lower()
    s = re.sub(r"[^a-z0-9-_]+", "-", s)
    s = re.sub(r"-{2,}", "-", s).strip("-")
    return s or "my-space"

def ensure_nonempty(prompt, initial=""):
    while True:
        val = simpledialog.askstring("Input required", prompt, initialvalue=initial)
        if val is None:
            raise SystemExit("Cancelled.")
        if val.strip():
            return val.strip()

def ask_yes_no(title, text):
    return bool(messagebox.askyesno(title, text))

# ----------------------------
# Styled Gradio app template (autogenerated)
# ----------------------------
APP_PY = dedent(r'''
    # app.py (autogenerated, styled)
    import os
    import json
    from pathlib import Path
    from string import Template
    import gradio as gr
    from openai import OpenAI

    BASE = Path(__file__).parent
    PI_DIR = BASE / "personal_info"
    PDF_DEST = PI_DIR / "linkedin_profile.pdf"
    PDF_URL_HINT = PI_DIR / "linkedin_pdf_url.txt"  # optional file containing a direct PDF URL
    
    def _get_openai_key():
        for k, v in os.environ.items():
            if k.strip().upper() == "OPENAI_API_KEY" and v:
                return v
        return os.getenv("OPENAI_API_KEY") or os.getenv("openai_api_key")

    OPENAI_API_KEY = _get_openai_key()
    OPENAI_READY = bool(OPENAI_API_KEY)

    SUMMARY = (PI_DIR / "summary.txt").read_text(encoding="utf-8") if (PI_DIR / "summary.txt").exists() else ""
    LINKEDIN_URL = (PI_DIR / "linkedin_url.txt").read_text(encoding="utf-8").strip() if (PI_DIR / "linkedin_url.txt").exists() else ""
    NAME = (PI_DIR / "name.txt").read_text(encoding="utf-8").strip() if (PI_DIR / "name.txt").exists() else "This professional"
    LOOKING_FLAG = (PI_DIR / "looking.json").read_text(encoding="utf-8") if (PI_DIR / "looking.json").exists() else '{"looking": false}'
    LOOKING_FOR_ROLE = json.loads(LOOKING_FLAG).get("looking", False)

    availability_instructions = (
        "AVAILABILITY:\\n"
        "- {name} is actively looking for a new position.\\n"
        "- When relevant, briefly note they’re exploring opportunities now.\\n"
        "- Ask 2–4 qualifying questions (scope, team/domain, remote/on-site, comp range, timeline).\\n"
        "- Be confident and concise—never sound desperate.\\n"
        if LOOKING_FOR_ROLE else
        "AVAILABILITY:\\n"
        "- {name} is not actively looking and is happy where they are.\\n"
        "- Be appreciative and neutral; avoid presenting as actively searching.\\n"
        "- Only request contact details if the opportunity sounds truly exceptional.\\n"
    ).format(name=NAME)

    SYSTEM_PROMPT = (
        f"You are acting as {NAME}. You are answering questions on {NAME}'s site, "
        "particularly about career, background, skills and experience. "
        "Use the provided summary and keep answers professional and concise. "
        "If unsure, say you’re not certain.\\n\\n"
        + availability_instructions +
        f"\\nSOURCE SUMMARY:\\n{SUMMARY}\\nLINKEDIN: {LINKEDIN_URL or '–'}\\n"
    )

    SAFE_REFUSAL = "I’m going to keep it professional and skip that. Happy to discuss experience, projects, and fit for roles."
                    
    def _try_fetch_pdf():
        """
        If personal_info/linkedin_pdf_url.txt exists, download that URL as linkedin_profile.pdf.
        Otherwise, if LINKEDIN_URL ends with .pdf, try that.
        Save to personal_info/linkedin_profile.pdf if content appears to be a PDF.
        """
        try:
            # Prefer explicit PDF URL file
            if PDF_URL_HINT.exists():
                url = PDF_URL_HINT.read_text(encoding="utf-8").strip()
            else:
                url = LINKEDIN_URL.strip() if LINKEDIN_URL.lower().endswith(".pdf") else ""

            if not url:
                return  # nothing to fetch

            headers = {"User-Agent": "Mozilla/5.0"}
            r = requests.get(url, timeout=20, headers=headers, stream=True)
            r.raise_for_status()

            # Check if it's likely a PDF
            ctype = r.headers.get("Content-Type", "").lower()
            if "application/pdf" in ctype or url.lower().endswith(".pdf"):
                # Write bytes to destination
                data = r.content  # fine for typical-sized PDFs
                PDF_DEST.parent.mkdir(parents=True, exist_ok=True)
                PDF_DEST.write_bytes(data)
                print(f"Saved PDF to {PDF_DEST}")
            else:
                print(f"Skipped saving: URL didn’t look like a PDF (content-type: {ctype})")

        except Exception as e:
            # Silent, non-fatal
            print(f"PDF fetch error: {e}")

    def moderate(text: str) -> bool:
        t = (text or "").lower()
        bad = ["fuck", "shit", "bitch", "bastard", "moron"]
        return any(w in t for w in bad)

    def chat_fn(message, history):
        if moderate(message):
            return SAFE_REFUSAL

        if not OPENAI_READY:
            return "This Space isn’t configured with an OPENAI_API_KEY yet (Settings → Variables & secrets)."

        messages = [{"role": "system", "content": SYSTEM_PROMPT}] + history + [{"role": "user", "content": message}]
        try:
            client = OpenAI()
            resp = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=messages,
                temperature=0.6,
            )
            return resp.choices[0].message.content
        except Exception as e:
            return f"OpenAI error: {e}"

    # Attempt once on startup
    _try_fetch_pdf()

    # ------- Styled UI (header HTML + CSS) -------
    # Palette
    G1 = "#2563EB"        # royal blue
    G2 = "#06B6D4"        # cyan
    TEXT_DARK = "#0F172A" # slate-900

    # Badge styles depend on availability
    if LOOKING_FOR_ROLE:
        BADGE_BG = "linear-gradient(135deg, #10b981, #22d3ee)"  # emerald -> cyan
        BADGE_COLOR = "#ffffff"
        BADGE_SHADOW = "0 8px 16px rgba(16,185,129,.28)"
        BADGE_TEXT = "Open to opportunities"
    else:
        BADGE_BG = "#e2e8f0"   # slate-200
        BADGE_COLOR = "#0f172a"
        BADGE_SHADOW = "inset 0 0 0 1px #cbd5e1"
        BADGE_TEXT = "Not actively looking"

    theme = gr.themes.Soft(
        primary_hue="indigo",
        secondary_hue="cyan",
        neutral_hue="slate",
        font=[gr.themes.GoogleFont("Inter"), "ui-sans-serif"],
        font_mono=[gr.themes.GoogleFont("Fira Code"), "ui-monospace"],
    )

    header_html = f"""
    <div class="hero">
    <div class="hero-left">
        <div class="hero-avatar"></div>
        <div class="hero-text">
        <div class="hero-title">Chat with {NAME}'s profile AI</div>
        <div class="notice" style="margin-top:20px;">
            <span class="dot"></span>
            <span class="text"><i>I’m an AI version of {NAME}. I’m still learning and may be wrong sometimes—please verify important info.</i></span>
        </div>
        </div>
    </div>
    <div class="hero-badge">{BADGE_TEXT}</div>
    </div>
    """

    _css_tpl = Template(r"""
    :root {
    --g1: $G1;
    --g2: $G2;
    --text-dark: $TEXT_DARK;
    --badge-bg: $BADGE_BG;
    --badge-color: $BADGE_COLOR;
    --badge-shadow: $BADGE_SHADOW;
    color-scheme: light;
    --chat-bg: #ffffff;
    }
    html, body { background: #f3f6fb; color: var(--text-dark); }
    #chat-shell {
    position: relative;
    max-width: 760px;
    margin: 32px auto;
    padding: 2px;
    border-radius: 18px;
    background: linear-gradient(135deg, var(--g1), var(--g2));
    box-shadow: 0 20px 50px rgba(2, 6, 23, 0.14);
    }
    #chat-inner {
    background: var(--chat-bg) !important;
    border-radius: 16px;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    }
    /* Header */
    .hero {
    position: relative;
    display: flex; align-items: center;
    justify-content: flex-start;
    background: linear-gradient(135deg, var(--g1), var(--g2));
    color: #fff;
    padding: 16px 18px;
    }
    .hero-left { display:flex; align-items:center; gap:12px; }
    .hero-avatar {
    width: 44px; height: 44px; border-radius: 50%;
    background: radial-gradient(ellipse at 30% 30%, #ffffff 0%, #dbeafe 35%, transparent 60%),
                linear-gradient(135deg, #60a5fa, #38bdf8);
    box-shadow: 0 6px 14px rgba(0,0,0,.18), inset 0 0 0 2px rgba(255,255,255,.35);
    }
    .hero-title { font-weight: 700; font-size: 18px; line-height: 1.2; }
    .hero-badge {
    position: absolute;
    top: 5px;
    right: 5px;
    z-index: 1;
    font-size: 12px; font-weight: 700; letter-spacing: .2px;
    padding: 8px 10px; border-radius: 9999px;
    background: var(--badge-bg); color: var(--badge-color);
    box-shadow: var(--badge-shadow);
    white-space: nowrap;
    }
    /* Chat container */
    #ci {
    background: var(--chat-bg) !important;
    border-radius: 0 0 16px 16px;
    padding: 8px 10px 8px;  /* small bottom padding so input sits low */
    color: var(--text-dark);
    }
    /* Turn the ChatInterface root into a flex column and set target height */
    #ci > div {
    display: flex !important;
    flex-direction: column !important;
    min-height: 550px !important;     /* total usable panel height */
    }
    /* Let the messages panel grow; remove fixed heights */
    #ci .gr-chatbot,
    #ci .chatbot {
    flex: 1 1 auto !important;
    height: auto !important;
    min-height: 0 !important;
    }
    /* Push the controls/input block to the bottom */
    #ci .wrap {               /* Retry/Undo/Clear + input form container */
    margin-top: auto !important;
    }
    #ci form {                /* the input row itself */
    margin-top: 0 !important;
    margin-bottom: 0 !important;
    }
    /* Visual styling */
    #ci .gr-chatbot,
    #ci .chatbot,
    #ci .gr-chatbot > div,
    #ci .chatbot > div,
    #ci .gr-box,
    #ci .gr-panel {
    background: var(--chat-bg) !important;
    }
    #ci .message.bot {
    background: #eef2f7 !important;
    color: var(--text-dark) !important;
    border: 1px solid #e5e7eb !important;
    border-radius: 14px !important;
    }
    #ci .message.bot *,
    #ci .message.bot .prose,
    #ci .message.bot .prose *,
    #ci .message.bot .markdown-body,
    #ci .message.bot .markdown-body * {
    color: var(--text-dark) !important;
    }
    #ci .message.bot a { color: #1d4ed8 !important; }
    #ci .message.bot code, #ci .message.bot pre {
    background: #f1f5f9 !important;
    color: #111827 !important;
    border-radius: 6px;
    padding: 0.1rem 0.3rem;
    }
    #ci .message.user {
    background: linear-gradient(135deg, var(--g1), var(--g2)) !important;
    color: #ffffff !important;
    border: none !important;
    border-radius: 14px !important;
    box-shadow: 0 6px 16px rgba(37,99,235,.25);
    }
    #ci .gr-chatbot { padding: 12px; }
    #ci .gr-chatbot, #ci .chatbot { filter: saturate(1.05) contrast(1.03); }
    #ci .gr-textbox {
    background: #f8fafc !important;
    border: 1.6px solid #cbd5e1 !important;
    border-radius: 14px !important;
    box-shadow: inset 0 1px 0 rgba(255,255,255,.6);
    }
    #ci .gr-textbox textarea {
    padding: 14px 16px !important;
    min-height: 56px !important;
    line-height: 1.4 !important;
    resize: none !important;
    color: var(--text-dark) !important;
    }
    #ci .gr-textbox textarea::placeholder { color: #64748b !important; opacity: .95 !important; }
    #ci .gr-textbox:focus-within {
    border-color: transparent !important;
    box-shadow:
        0 0 0 2px rgba(37,99,235,.35),
        0 0 0 5px rgba(6,182,212,.20),
        inset 0 1px 0 rgba(255,255,255,.6) !important;
    }
    #ci .gr-form, #ci .gradio-row { gap: 10px; }
    #ci button.gr-button.primary {
    width: 46px; min-width: 46px; height: 46px;
    padding: 0 !important;
    border-radius: 9999px !important;
    background: linear-gradient(135deg, var(--g1), var(--g2)) !important;
    border: 0 !important;
    color: #fff !important;
    box-shadow: 0 10px 22px rgba(37,99,235,.28);
    display: inline-flex; align-items: center; justify-content: center;
    }
    #ci button.gr-button.primary:hover { filter: brightness(1.06); transform: translateY(-1px); }
    #ci button.gr-button.primary:active { transform: translateY(0); filter: brightness(0.98); }
    #ci button.gr-button { border-radius: 12px !important; }
    @media (prefers-color-scheme: dark) {
    html, body { background: #f3f6fb !important; color: var(--text-dark) !important; }
    #chat-inner, #ci, #ci .gr-chatbot, #ci .chatbot, #ci .gr-box, #ci .gr-panel, .gradio-container {
        background: var(--chat-bg) !important;
    }
    #ci .message.bot { background: #e5e7eb !important; }
    #ci .message.bot *, #ci .gr-markdown * { color: var(--text-dark) !important; }
    }
    @media screen and (max-width: 480px) {
    #chat-inner, #ci, #ci .gr-chatbot, #ci .chatbot { background: var(--chat-bg) !important; }
    }
    .gradio-container { padding: 12px; }
    """)


    css = _css_tpl.substitute(
        G1=G1, G2=G2, TEXT_DARK=TEXT_DARK,
        BADGE_BG=BADGE_BG, BADGE_COLOR=BADGE_COLOR, BADGE_SHADOW=BADGE_SHADOW
    )


    with gr.Blocks(theme=theme, css=css, title=f"Chat with {NAME}") as demo:
        with gr.Group(elem_id="chat-shell"):
            with gr.Column(elem_id="chat-inner"):
                gr.HTML(header_html, elem_id="hero")
                with gr.Group(elem_id="ci"):
                    # Make the visible chat area 700px tall
                    chatbot = gr.Chatbot(type="messages", height=700, show_copy_button=True)
                    gr.ChatInterface(
                        chat_fn,
                        chatbot=chatbot,
                        type="messages",
                        title=None,
                        description=None,
                    )

    if __name__ == "__main__":
        demo.launch()
''').strip("\n")



# Requirements: pin to same version as README sdk_version to avoid config errors
REQS_TXT = """\
gradio==4.44.1
openai>=1.40
python-dotenv
requests
"""

# README with HF Repo Card front-matter
README_TMPL = Template("""\
---
title: $display_name – Personal Career Chat
emoji: 🤖
colorFrom: indigo
colorTo: green
sdk: gradio
sdk_version: "4.44.1"
app_file: app.py
pinned: false
---

# Personal Career Chat for $display_name

This Space was created automatically. It hosts a simple Gradio chat UI backed by OpenAI.

## Configure
- Add your `OPENAI_API_KEY` in **Settings → Variables & secrets → New secret**.
- Click **Restart** if the Space is still building.

## Files
- `app.py` – Gradio app.
- `personal_info/summary.txt` – your short bio/summary.
- `personal_info/linkedin_url.txt` – your LinkedIn URL.
- `personal_info/name.txt` – your display name.
- `personal_info/looking.json` – `{"looking": true/false}`.

## Notes
- If you change your secrets or files, restart the Space to pick up changes.
""")

# ----------------------------
# Main flow
# ----------------------------
def main():
    # Tk bootstrap
    root = Tk()
    root.withdraw()

    messagebox.showinfo("Create HF Space", "We’ll create a Hugging Face Space for your LinkedIn chat.")

    # Gather all text inputs first
    hf_token = ensure_nonempty("Paste your Hugging Face WRITE token (Settings → Access Tokens)")
    openai_key = ensure_nonempty("Paste your OpenAI API key (starts with 'sk-...' or org-level key)")
    display_name = ensure_nonempty("Your display name (e.g., 'Robert Morrow')", initial="Your Name")
    linkedin_url = ensure_nonempty("Your LinkedIn profile URL (https://...)", initial="https://www.linkedin.com/in/")
    summary = ensure_nonempty("Write a short 3–6 sentence professional summary about yourself")
    space_name_input = ensure_nonempty("Pick a short Space name (letters/dashes). Example: career-conversation", initial="career-conversation")
    space_slug = slugify(space_name_input)

    # Yes/No after text questions
    looking = ask_yes_no("Availability", "Are you currently open to new opportunities?")
    private_space = ask_yes_no("Visibility", "Make the Space **private**? (Click 'No' for public)")

    # HF client & username
    api = HfApi(token=hf_token)
    who = api.whoami()
    user = who.get("name") or who.get("fullname") or who.get("id")

    # Create repo (Space) with conflict handling loop
    while True:
        try:
            create_repo(
                repo_id=space_slug,
                token=hf_token,
                repo_type="space",
                space_sdk="gradio",
                private=private_space,
                exist_ok=False,
            )
            break  # success
        except Exception as e:
            msg = str(e)
            if "409" in msg or "already exists" in msg or "You already created this space repo" in msg:
                messagebox.showwarning("Name taken", f"The Space name '{space_slug}' is already in use.\n\nPlease choose a new name.")
                space_name_input = ensure_nonempty("Pick a NEW short Space name (letters/dashes).", initial=f"{space_slug}-1")
                space_slug = slugify(space_name_input)
                continue
            else:
                messagebox.showerror("Repo creation failed", f"Could not create the Space:\n\n{e}")
                raise

    repo_id = f"{user}/{space_slug}"

    # Save secret
    try:
        api.add_space_secret(repo_id=repo_id, key="OPENAI_API_KEY", value=openai_key)
    except Exception as e:
        messagebox.showwarning(
            "Secret error",
            f"Could not set OPENAI_API_KEY as a Space secret:\n{e}\n\n"
            "You can also set it manually in the Space Settings."
        )

    # Upload files
    with tempfile.TemporaryDirectory() as td:
        td = os.path.abspath(td)
        os.makedirs(os.path.join(td, "personal_info"), exist_ok=True)

        # Write app + assets
        with open(os.path.join(td, "app.py"), "w", encoding="utf-8") as f:
            f.write(APP_PY)

        with open(os.path.join(td, "requirements.txt"), "w", encoding="utf-8") as f:
            f.write(REQS_TXT)

        with open(os.path.join(td, "README.md"), "w", encoding="utf-8") as f:
            f.write(README_TMPL.substitute(display_name=display_name))

        with open(os.path.join(td, "personal_info", "summary.txt"), "w", encoding="utf-8") as f:
            f.write(summary)

        with open(os.path.join(td, "personal_info", "linkedin_url.txt"), "w", encoding="utf-8") as f:
            f.write(linkedin_url)

        with open(os.path.join(td, "personal_info", "name.txt"), "w", encoding="utf-8") as f:
            f.write(display_name)

        with open(os.path.join(td, "personal_info", "looking.json"), "w", encoding="utf-8") as f:
            f.write(json.dumps({"looking": bool(looking)}))

        # Helper to upload
        def up(local_path, dest_path):
            upload_file(
                path_or_fileobj=local_path,
                path_in_repo=dest_path,
                repo_id=repo_id,
                repo_type="space",
                token=hf_token,
            )

        # Push files
        up(os.path.join(td, "app.py"), "app.py")
        up(os.path.join(td, "requirements.txt"), "requirements.txt")
        up(os.path.join(td, "README.md"), "README.md")
        up(os.path.join(td, "personal_info", "summary.txt"), "personal_info/summary.txt")
        up(os.path.join(td, "personal_info", "linkedin_url.txt"), "personal_info/linkedin_url.txt")
        up(os.path.join(td, "personal_info", "name.txt"), "personal_info/name.txt")
        up(os.path.join(td, "personal_info", "looking.json"), "personal_info/looking.json")

    url = f"https://huggingface.co/spaces/{repo_id}"
    messagebox.showinfo("All set!", f"Your Space is ready:\n\n{url}\n\nIf it’s not live yet, it’s just building—refresh shortly.")
    print(url)

if __name__ == "__main__":
    # make Tk crisp on HiDPI (Windows)
    try:
        import ctypes
        ctypes.windll.shcore.SetProcessDpiAwareness(1)
    except Exception:
        pass
    main()
